name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java (needed for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Install Android SDK
      - name: Install Android SDK
        uses: r0adkll/install-android-sdk@v2

      # 4. Make Gradle executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. Build project
      - name: Build with Gradle
        run: ./gradlew build

      # 6. Run tests
      - name: Run tests
        run: ./gradlew test
